"use client";

import { useEffect, useRef, useState, type CSSProperties, type MouseEvent } from "react";
type Point = { x: number; y: number };
const W = 1000, H = 562.5;
const dist = (a: Point, b: Point) => Math.hypot((a.x-b.x)*W, (a.y-b.y)*H);
const rawArea = (p: Point[]) => Math.abs(p.reduce((s,a,i) => { const b=p[(i+1)%p.length]; return s+a.x*b.y-b.x*a.y; },0))/2;
export default function Scanner3DTestPage() {
 const video=useRef<HTMLVideoElement>(null), stream=useRef<MediaStream|null>(null);
 const [active,setActive]=useState(false),[points,setPoints]=useState<Point[]>([]),[meters,setMeters]=useState("4.20"),[ready,setReady]=useState(false),[msg,setMsg]=useState("");
 useEffect(()=>()=>stream.current?.getTracks().forEach(t=>t.stop()),[]);
 const real=Number(meters.replace(",",".")), scale=points.length>1&&dist(points[0],points[1])?real/dist(points[0],points[1]):0;
 const area=ready&&scale&&points.length>=3?rawArea(points)*W*H*scale*scale:0;
 const edges=ready&&scale?points.map((p,i)=>dist(p,points[(i+1)%points.length])*scale):[];
 async function openCamera(){setMsg("");try{const s=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:{ideal:"environment"}}});stream.current=s;if(video.current){video.current.srcObject=s;await video.current.play()}setActive(true)}catch{setMsg("Não foi possível abrir a câmera. Confira a permissão e tente em HTTPS.")}}
 function closeCamera(){stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;if(video.current)video.current.srcObject=null;setActive(false)}
 function mark(e:MouseEvent<HTMLDivElement>){if(!active||ready)return;const r=e.currentTarget.getBoundingClientRect();setPoints(p=>[...p,{x:Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))}])}
 function reset(){closeCamera();setPoints([]);setReady(false);setMsg("")}
 function calibrate(){if(points.length<3){setMsg("Marque pelo menos três cantos do ambiente.");return}if(!Number.isFinite(real)||real<=0){setMsg("Informe uma distância válida entre os pontos 1 e 2.");return}setReady(true);setMsg("Planta estimada. Confira as medidas com trena.")}
 const card:CSSProperties={background:"#fff",border:"1px solid #d9d2c0",borderRadius:14,padding:18,boxShadow:"0 5px 18px #141f220d"};
 const btn:CSSProperties={border:0,borderRadius:9,padding:"10px 14px",background:"#205e73",color:"white",fontWeight:800,cursor:"pointer"};
 return <main style={{minHeight:"calc(100vh - 58px)",background:"#f5f1e9",color:"#141f22",padding:"30px clamp(16px,4vw,56px) 60px"}}><div style={{maxWidth:1240,margin:"0 auto"}}>
 <p style={{color:"#56635f",fontSize:13}}>Projeto Laudo / Laboratório</p><header style={{display:"flex",flexWrap:"wrap",alignItems:"end",justifyContent:"space-between",gap:16,marginBottom:22}}><div><span style={{color:"#205e73",fontWeight:800,fontSize:11,letterSpacing:".12em"}}>PROTÓTIPO EXPERIMENTAL</span><h1 style={{margin:"8px 0",color:"#0f2f3a",fontSize:"clamp(30px,4vw,46px)"}}>Scanner de ambientes</h1><p style={{maxWidth:720,margin:0,color:"#56635f",lineHeight:1.6}}>Marque os cantos pela câmera, calibre com uma distância real e veja uma planta baixa estimada. Nada é salvo no projeto.</p></div><strong style={{background:"#f7e3cc",color:"#7f4a14",borderRadius:99,padding:"8px 12px",fontSize:12}}>Somente para testes</strong></header>
 <div style={{display:"flex",flexWrap:"wrap",alignItems:"start",gap:16}}><section style={{...card,flex:"2 1 520px",padding:0,overflow:"hidden"}} aria-label="Câmera e marcação"><div onClick={mark} style={{position:"relative",aspectRatio:"16 / 9",background:"#172529",overflow:"hidden",cursor:active&&!ready?"crosshair":"default",touchAction:"manipulation"}}>{active&&<video ref={video} autoPlay muted playsInline style={{position:"absolute",inset:0,width:"100%",height:"100%",objectFit:"cover"}}/>}{!active&&<div style={{position:"absolute",inset:0,display:"grid",placeContent:"center",gap:9,textAlign:"center",padding:24,color:"#f5f1e9"}}><b>A câmera aparece aqui</b><span style={{fontSize:12}}>Abra a câmera traseira para marcar os cantos do ambiente.</span></div>}<span style={{position:"absolute",top:12,left:12,padding:"7px 10px",borderRadius:99,color:"white",background:"#0a161bcc",fontSize:11,fontWeight:800}}>{active?"● CÂMERA ATIVA":"○ AGUARDANDO CÂMERA"} · {points.length} pontos</span>{points.map((p,i)=><span key={i} style={{position:"absolute",left:p.x*100+"%",top:p.y*100+"%",transform:"translate(-50%,-50%)",display:"grid",placeItems:"center",width:27,height:27,borderRadius:99,border:"2px solid white",background:"#d97b1f",color:"#0f2f3a",fontWeight:900}}>{i+1}</span>)}<span style={{position:"absolute",bottom:12,left:12,padding:9,borderRadius:8,color:"white",background:"#0a161bcc",fontSize:12}}>{active?"Toque nos cantos do piso em sequência.":"A câmera não está transmitindo."}</span></div><div style={{display:"flex",flexWrap:"wrap",gap:8,padding:13,borderTop:"1px solid #d9d2c0"}}><button style={btn} onClick={active?closeCamera:openCamera}>{active?"Parar câmera":"Abrir câmera"}</button><button style={{...btn,background:"white",color:"#141f22",border:"1px solid #d9d2c0"}} onClick={()=>{setPoints(p=>p.slice(0,-1));setReady(false)}}>Desfazer ponto</button><button style={{...btn,background:"white",color:"#141f22",border:"1px solid #d9d2c0"}} onClick={reset}>Limpar</button></div></section>
 <aside style={{flex:"1 1 290px",minWidth:0,display:"grid",gap:14}}><section style={card}><h2 style={{margin:"0 0 5px",color:"#0f2f3a",fontSize:18}}>Calibrar leitura</h2><p style={{margin:0,color:"#56635f",fontSize:12,lineHeight:1.5}}>Marque os pontos 1 e 2 numa mesma parede e informe a distância medida com trena.</p><label style={{display:"block",marginTop:12,color:"#56635f",fontSize:12,fontWeight:700}}>Distância real entre pontos 1 e 2 (m)<input style={{display:"block",width:"100%",boxSizing:"border-box",marginTop:5,border:"1px solid #d9d2c0",borderRadius:8,padding:10}} type="number" min=".1" step=".01" value={meters} onChange={e=>{setMeters(e.target.value);setReady(false)}}/></label><button style={{...btn,width:"100%",marginTop:12,background:"#2e755b"}} onClick={calibrate}>Gerar planta estimada</button>{msg&&<p role="status" style={{color:"#205e73",fontSize:12}}>{msg}</p>}<p style={{margin:"12px 0 0",padding:10,borderRadius:8,background:"#f7e3cc",color:"#68441d",fontSize:12,lineHeight:1.5}}><b>Precisão:</b> câmera comum não garante medidas 3D. Perspectiva, luz e movimento distorcem a escala; confira tudo com trena.</p></section>
 <section style={card}><h2 style={{margin:"0 0 5px",color:"#0f2f3a",fontSize:18}}>Planta baixa</h2><p style={{margin:0,color:"#56635f",fontSize:12}}>Contorno 2D aproximado dos pontos marcados.</p><svg viewBox="0 0 320 220" width="100%" role="img" aria-label="Prévia da planta estimada" style={{marginTop:12,border:"1px solid #d9d2c0",borderRadius:10,background:"#fbfaf7"}}><defs><pattern id="grid" width="16" height="16" patternUnits="userSpaceOnUse"><path d="M16 0H0V16" fill="none" stroke="#e7e1d4" strokeWidth=".7"/></pattern></defs><rect width="320" height="220" fill="url(#grid)"/>{points.length>=3&&<><polygon points={points.map(p=>(28+p.x*264)+","+(24+p.y*172)).join(" ")} fill="rgba(32,94,115,.12)" stroke="#205e73" strokeWidth="3" strokeDasharray={ready?"0":"7 5"}/>{ready&&<text x="160" y="112" textAnchor="middle" fontSize="13" fontWeight="800" fill="#0f2f3a">{area.toFixed(2)} m²*</text>}</>}{points.length<3&&<text x="160" y="112" textAnchor="middle" fill="#8b968f" fontSize="12">Marque ao menos 3 cantos</text>}</svg>{ready&&<><p style={{color:"#0f2f3a",fontWeight:900,fontSize:20}}>Área estimada: {area.toFixed(2)} m²*</p><div style={{display:"flex",flexWrap:"wrap",gap:6}}>{edges.map((v,i)=><span key={i} style={{padding:"6px 8px",borderRadius:7,background:"#f5f1e9",color:"#56635f",fontSize:11}}>Lado {i+1}: <b>{v.toFixed(2)} m*</b></span>)}</div></>}<p style={{margin:"10px 0 0",color:"#8b968f",fontSize:11}}>*Estimativa demonstrativa; não usar como medida técnica final.</p></section><section style={{...card,background:"#edf3f4"}}><b style={{color:"#0f2f3a"}}>Onde a IA ajuda</b><p style={{margin:"6px 0 0",color:"#56635f",fontSize:12,lineHeight:1.5}}>Pode sugerir paredes, portas e contornos, mas não garante metragem. Este teste não envia imagens à OpenAI; o uso da API é cobrado separadamente do ChatGPT Plus.</p></section></aside></div><p style={{marginTop:18,color:"#8b968f",fontSize:11}}>Laboratório isolado. Nenhuma captura é salva, anexada à vistoria ou exportada para um laudo.</p></div></main>;
}
